name: 617 error

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: 'Set up Java 8+'
        uses: actions/setup-java@v4
        with:
          java-version: |
            21
            17
            14
            11
            8
          distribution: 'temurin'
      - name: 'Set up Java 6/7'
        uses: actions/setup-java@v4
        with:
          java-version: |
            7
            6
          distribution: 'zulu'
      - name: Show Toolchain
        run: cat ~/.m2/toolchains.xml
      - name: Show location
        run: pwd
      - name: List current directory
        run: ls -l
      - name: Maven version
        run: mvn --version
      - name: Maven Install
        run: mvn clean install
