name: 617 error

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_subdirectory
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: 'Set up Java 6/7/14'
        uses: actions/setup-java@v4
        with:
          java-version: |
            14
            7
            6
            25-ea
          distribution: 'zulu'
      - name: 'Set up Java 8/11/17/21+'
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            11
            8
            21
          distribution: 'temurin'
      - name: Show Toolchain and settings
        run: cat ~/.m2/toolchains.xml ~/.m2/settings.xml
      - name: Show location
        run: pwd
      - name: List current directory
        run: ls -l
      - name: Scan JDKs
        run: grep -oP '(?<=<jdkHome>)[^<]++' ~/.m2/toolchains.xml
      - name: Maven version
        run: mvn --version
