name: Release

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my_subdirectory
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: 'Set up Java 6/7/14'
        uses: actions/setup-java@v4
        with:
          java-version: |
            14
            7
            6
          distribution: 'zulu'
      - name: 'Set up Java 8/11/17/21+'
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            11
            8
            21
          distribution: 'temurin'
      - name: Break release
        run: echo break release ...; echo continue | perl -pe 's/$/ release' | grep -o 'continue ....'
      - name: Show location
        run: pwd
      - name: Maven version
        run: mvn --version
      - name: Configure Git User
        run: |
          git config user.email "${GITHUB_ACTOR}"
          git config user.name "GitHub Actions"
      - name: Maven Release
        run: mvn --batch-mode release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
